


svenska_nyckelord = {
    "Dataanalys",
    "Data engineering",
    "Business"
    "intelligence" 
    "BI",
    "affär",
    "logik",
    "affärslogik",
    "Maskininlärning",
    "ML",
    "ETL",
    "Extrahera", 
    "Transformera", 
    "Ladda",
    "Data",
    "warehous",
    "varuhus",
    "Datavisualisering",
    "visual",
    "KPI-dashboards",
    "Kravanalys",
    "Tidsserieanalys",
    "Tidsserie",
    "Prestandarapportering",
    "Metadatahantering",
    "meta",
    "Logg",
    "dataanalys",
    "Lineagerapportering",
    "Prestanda",
    "övervakning",
    "Automatisering",
    "Automat",
    "Schemaläggning",
    "Schema",
    "orkest",
    "SQL",
    "Python",
    "SAS",
    "vault",
    "Data Vault-modellering",
    "Kimball",
    "modellering",
    "modell",
    "Agil",
    "Scrum",
    "CI",
    "CD",
    "Continuous",
    "Integration",
    "Deployment",
    "Versions",
    "kontroll",
    "Problemlösning",
    "Kommunikation",
    "Molnbaserad databehandling (GCP, Vertex AI)",
    "Moln",
    "behandling" ,
    "GCP",
    "Vertex",
    "AI",
    "Data Lake",
    "lakehouse",
    "Gedigen",
    "erfarenhet",
    "Expert",
    "kunskaper",
    "SVM",
    "Vector" ,
    "Machine",
    "Random",
    "Forest",
    "Deep", 
    "Neural", 
    "Networks",
    "Keras",
    "XGBoost",
    "Tree",
    "Regressor",
    "One-hot",
    "encod",
    "Dataanalytiker",
    "analy",
    "Verksamhet",
    "Databasutvecklare",
    "Databas",
    "utvecklare",
    "BI",
    "Dataingenjör",
    "ETL-utvecklare",
    "ETL",
    "ML-engineer",
    "ML",
    "engineer",
    "Systemutvecklare",
    "System",
    "System",
    "Statistiker",
    "Airflow",
    "Kubeflow",
    "Vertex",
    "AI",
    "Power BI",
    "Qlik",
    "SAS DI",
    "sas",
    "integration",
    "SSIS",
    "MSSQL",
    "SQL Server",
    "sql",
    "Oracle",
    "PL/SQL",
    "BigQuery",
    "Hadoop",
    "Visual Studio Code",
    "vsc",
    "visual studio",
    "MinIO",
    "DBT",
    "SSRS",
    "SSAS",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "TFS Azure DevOps",
    "Databricks",
    "Spark SQL"
}







keywords = {
    "analysis",
    "Data",
    "engineering",
    "Business",
    "intelligence" ,
    "BI",
    "Machine",
    "learning",
    "ML",
    "ETL",
    "Extract", 
    "Transform", 
    "Load",
    "warehous",
    "visualization",
    "KPI",
    "dashboards",
    "Requirements ",
    "Time series",
    "series",
    "Performance" ,
    "reporting",
    "Meta",
    "management",
    "Log",
    "Lineage",
    "Performance",
    "monitoring",
    "Automation",
    "Scheduling",
    "SQL",
    "Python",
    "SAS",
    "inmon",
    "normal",
    "dimension",
    "scd",
    "slowly",
    "changing",
    "test",
    "Vault", 
    "modeling",
    "Kimball",
    "Agile",
    "Scrum",
    "CI",
    "CD",
    "Continuous",
    "Integration",
    "Deployment",
    "Version",
    "Problem",
    "Communication",
    "Cloud",
    "GCP",
    "Vertex",
    "AI",
    "Data Lake",
    "experienced",
    "expert",
    "deep",
    "SVM", 
    "Vector",
    "neighbor",
    "random", 
    "Forest",
    "Deep", 
    "Neural",
    "Keras",
    "XGBoost", 
    "Data Engineer",
    "Data Analyst",
    "Data Scientist",
    "Engine",
    "Analy",
    "Scien",
    "analyst",
    "Developer",
    "ETL Developer",
    "ML Engineer",
    "Statistician",
    "Business Intelligence Developer",
    "Business",
    "Intelligence",
    "Developer",
    "Airflow",
    "Kubeflow",
    "Vertex AI",
    "Power BI",
    "Qlik",
    "SAS DI",
    "SSIS",
    "MSSQL",
    "SQL Server",
    "Oracle",
    "PL/SQL",
    "sql",
    "GCP",
    "BigQuery",
    "Hadoop",
    "Visual Studio Code",
    "visual studio",
    "vsc",
    "MinIO",
    "DBT",
    "SSRS",
    "SSAS",
    "GitHub",
    "GitLab",
    "git",
    "Bitbucket",
    "TFS Azure DevOps",
    "tfs",
    "azure",
    "devops",
    "Databricks",
    "Spark"
}

